### ISSUE TITLE
Add real-time safe Rotation type

### ISSUE THREAD

**Issue by ndehio** [cogimon/cogimon.github.io#13]
Please add a real-time safe Rotation type.
Some additional functions for conversion between EulerZYX <-> AxisAngle <-> Quaternion <-> RotationMatrix would be highly beneficial.

Maybe the implementation can be based upon the kdl-rotation type:
http://docs.ros.org/hydro/api/orocos_kdl/html/classKDL_1_1Rotation.html

**Comment by xwavex** [comment]
see rstrt types

**Comment by ndehio** [comment]
Sure, there is an Rotation type:
https://github.com/corlab/rst-rt/blob/master/src/rst-rt/geometry/Rotation.hpp

However, we are missing functions for conversion between different rotation representations.
