### ISSUE TITLE
Update Cosima installation tutorial

### ISSUE THREAD

**Issue by ndehio** [cogimon/cogimon.github.io#15]
We installed the Cosima software on Ubuntu 16.04.
Two dependencies were missing:
sudo apt-get install libyaml-cpp-dev
sudo apt-get install libgtest-dev

In addition, we use openjdk-8-jdk instead of openjdk-7-jdk.
Please add this info to the installation tutorial.

There are also inconsistencies regarding different versions for Gazebo in the documentation
sudo apt-get install gazebo7
sudo apt-get install libgazebo6-dev

**Comment by ndehio** [comment]
Finally, I also had to install:
sudo apt-get install liburdfdom-dev

Please add it to the documentation webpage

**Comment by ndehio** [comment]
~Please add also to the installation tutorial that one might need another build-generator, which can be downloaded here:
https://ci.cor-lab.org/job/build-generator-trunk/~

**Comment by xwavex** [comment]
@ndehio Thx! Looks like now we have everything updated on http://cogimon.github.io/software/gettingstarted.html
