### ISSUE TITLE
Apply External Force to Robot Feature 

### ISSUE THREAD

**Issue by ndehio** [cogimon/cogimon.github.io#19]
In the Gazebo-Gui one can easily apply external forces to specific robot-links.
How can we apply external forces automatically by an orocos component in simulation?
Please extend the gazebo/robot-sim interface. 

We discussed this feature already 12 month ago. It is highly necessary to simulate human-like disturbances as we will need for the two cogimoin scenarios "human-coman carrying a table" and "dual-kuka setup manipulation tasks"

**Comment by xwavex** [comment]
Nice that you are looking into it. Please create a detailed specification and submit a (C++) proposal. I will then review it before we officially release it.

**Comment by ndehio** [comment]
Well, as far as I understand the simulation bridge, one need to add new input ports (e.g.. "in_externalForce_LElb") for each robot link which expects to read our realtime-type "Force".
Alternatively, we can add such ports for each kinematic chain and expect a vector of three-dimensional "Forces".

Both ways a user can specify an external force for each link in each time step.
Once the simulation bridge receives such forces it should apply them immediately to the center of mass of the specified links. I don't know how this will work in detail.

**Comment by xwavex** [comment]
i think we should not do it inside the robot simulation component

**Comment by xwavex** [comment]
this is related to https://github.com/cogimon/cogimon.github.io/issues/22

**Comment by ndehio** [comment]
I just added a component "GazeboForceTorqueExerter" into our cosima-projected-dynamics repo and provide a simple example in the ops file https://github.com/cogimon/cosima-projected-dynamics/blob/master/ops/SimpleKDLExample.ops
