### ISSUE TITLE
IMU type in rtt-rrct-description

### ISSUE THREAD

**Issue by OpenSoT** [cogimon/cogimon.github.io#27]
To broadcast data fro the IMU in OROCOS we need the following 3 data types:

1. Linear Acceleration **(ax, ay, az)**
2. Angular Velocity ~(wx, wy, wz)~ -> **(va, vb, vc)**
3. Orientation (~RPY,~ **quaternion**, ~any other parametrization...~) -> **(qw, qx, qy, qz)**

updated by: @xwavex

**Comment by xwavex** [comment]
Added types in
https://github.com/corlab/rst-rt/commit/866946b2953b3e1847d7da1727975e4912bd7870
and
https://github.com/corlab/rtt-rst-rt-typekit/commit/6f2e0981e046f7880bf40ddfdb562a0a4bcd6d56

Create IMU object:
```c++
rstrt::robot::IMU(rstrt::geometry::LinearAcceleration la, rstrt::geometry::AngularVelocity av, rstrt::geometry::Rotation rotation r);
```
or
```c++
rstrt::robot::IMU(ax, ay, az, va, vb, vc, qw, qx, qy, qz);
```
